import { drizzle } from "drizzle-orm/mysql2";
import { jobs } from "./drizzle/schema.js";

const db = drizzle(process.env.DATABASE_URL);

const sampleJobs = [
  {
    externalId: "web3career-001",
    source: "web3.career",
    title: "Senior Smart Contract Engineer",
    company: "Uniswap Labs",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 150000,
    salaryMax: 250000,
    salaryCurrency: "USD",
    description: "We're looking for an experienced Smart Contract Engineer to build the next generation of DeFi protocols.",
    requirements: "5+ years Solidity, auditing experience, DeFi knowledge",
    tags: JSON.stringify(["Solidity", "DeFi", "Smart Contracts", "Ethereum"]),
    applyUrl: "https://jobs.web3.career/uniswap-smart-contract",
    postedDate: new Date("2026-01-10"),
    isActive: 1,
  },
  {
    externalId: "cryptojobs-002",
    source: "cryptojobslist",
    title: "Blockchain Developer",
    company: "Coinbase",
    location: "San Francisco, CA",
    jobType: "Full-time",
    salaryMin: 140000,
    salaryMax: 220000,
    salaryCurrency: "USD",
    description: "Join Coinbase to build secure and scalable blockchain infrastructure.",
    requirements: "3+ years blockchain development, Rust or Go experience",
    tags: JSON.stringify(["Blockchain", "Rust", "Go", "Infrastructure"]),
    applyUrl: "https://cryptojobslist.com/coinbase-blockchain-dev",
    postedDate: new Date("2026-01-11"),
    isActive: 1,
  },
  {
    externalId: "remote3-003",
    source: "remote3",
    title: "Web3 Frontend Developer",
    company: "Aave",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 120000,
    salaryMax: 180000,
    salaryCurrency: "USD",
    description: "Build beautiful and intuitive DeFi interfaces for millions of users.",
    requirements: "React, TypeScript, Web3.js/Ethers.js, wallet integration",
    tags: JSON.stringify(["React", "TypeScript", "Web3", "Frontend"]),
    applyUrl: "https://remote3.co/aave-frontend",
    postedDate: new Date("2026-01-12"),
    isActive: 1,
  },
  {
    externalId: "solana-004",
    source: "jobs.solana.com",
    title: "Solana Core Developer",
    company: "Solana Foundation",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 160000,
    salaryMax: 240000,
    salaryCurrency: "USD",
    description: "Work on the Solana blockchain core protocol and validator infrastructure.",
    requirements: "Rust expert, distributed systems, blockchain protocols",
    tags: JSON.stringify(["Rust", "Solana", "Blockchain", "Protocol"]),
    applyUrl: "https://jobs.solana.com/core-developer",
    postedDate: new Date("2026-01-13"),
    isActive: 1,
  },
  {
    externalId: "telegram-005",
    source: "telegram",
    title: "DeFi Protocol Engineer",
    company: "Curve Finance",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 140000,
    salaryMax: 200000,
    salaryCurrency: "USD",
    description: "Design and implement innovative DeFi protocols and liquidity mechanisms.",
    requirements: "Solidity, DeFi protocols, mathematical modeling",
    tags: JSON.stringify(["Solidity", "DeFi", "Math", "Protocol Design"]),
    applyUrl: "https://curve.fi/careers",
    postedDate: new Date("2026-01-12"),
    isActive: 1,
  },
  {
    externalId: "web3career-006",
    source: "web3.career",
    title: "Security Engineer",
    company: "OpenZeppelin",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 150000,
    salaryMax: 230000,
    salaryCurrency: "USD",
    description: "Conduct smart contract audits and build security tools for Web3.",
    requirements: "Smart contract auditing, security research, Solidity",
    tags: JSON.stringify(["Security", "Auditing", "Solidity", "Web3"]),
    applyUrl: "https://jobs.web3.career/openzeppelin-security",
    postedDate: new Date("2026-01-11"),
    isActive: 1,
  },
  {
    externalId: "cryptojobs-007",
    source: "cryptojobslist",
    title: "NFT Platform Engineer",
    company: "OpenSea",
    location: "New York, NY",
    jobType: "Full-time",
    salaryMin: 130000,
    salaryMax: 190000,
    salaryCurrency: "USD",
    description: "Build scalable NFT marketplace infrastructure and APIs.",
    requirements: "Backend engineering, databases, API design, NFT standards",
    tags: JSON.stringify(["Backend", "NFT", "API", "Scalability"]),
    applyUrl: "https://cryptojobslist.com/opensea-engineer",
    postedDate: new Date("2026-01-10"),
    isActive: 1,
  },
  {
    externalId: "remote3-008",
    source: "remote3",
    title: "Blockchain Data Analyst",
    company: "Dune Analytics",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 90000,
    salaryMax: 140000,
    salaryCurrency: "USD",
    description: "Analyze on-chain data and build dashboards for the crypto community.",
    requirements: "SQL, Python, data visualization, blockchain knowledge",
    tags: JSON.stringify(["Data Analysis", "SQL", "Python", "Blockchain"]),
    applyUrl: "https://remote3.co/dune-analyst",
    postedDate: new Date("2026-01-13"),
    isActive: 1,
  },
  {
    externalId: "solana-009",
    source: "jobs.solana.com",
    title: "Rust Engineer",
    company: "Magic Eden",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 130000,
    salaryMax: 190000,
    salaryCurrency: "USD",
    description: "Build high-performance NFT marketplace on Solana.",
    requirements: "Rust, Solana programs, performance optimization",
    tags: JSON.stringify(["Rust", "Solana", "NFT", "Performance"]),
    applyUrl: "https://jobs.solana.com/magic-eden-rust",
    postedDate: new Date("2026-01-12"),
    isActive: 1,
  },
  {
    externalId: "telegram-010",
    source: "telegram",
    title: "Web3 Product Manager",
    company: "Metamask",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 140000,
    salaryMax: 200000,
    salaryCurrency: "USD",
    description: "Lead product strategy for the world's leading Web3 wallet.",
    requirements: "Product management, Web3 experience, user research",
    tags: JSON.stringify(["Product", "Web3", "Wallet", "Strategy"]),
    applyUrl: "https://metamask.io/careers",
    postedDate: new Date("2026-01-11"),
    isActive: 1,
  },
  {
    externalId: "web3career-011",
    source: "web3.career",
    title: "DevOps Engineer",
    company: "Chainlink Labs",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 130000,
    salaryMax: 180000,
    salaryCurrency: "USD",
    description: "Manage infrastructure for decentralized oracle networks.",
    requirements: "Kubernetes, AWS, CI/CD, monitoring, blockchain nodes",
    tags: JSON.stringify(["DevOps", "Kubernetes", "AWS", "Infrastructure"]),
    applyUrl: "https://jobs.web3.career/chainlink-devops",
    postedDate: new Date("2026-01-10"),
    isActive: 1,
  },
  {
    externalId: "cryptojobs-012",
    source: "cryptojobslist",
    title: "Smart Contract Auditor",
    company: "Trail of Bits",
    location: "Remote",
    jobType: "Contract",
    salaryMin: 150000,
    salaryMax: 250000,
    salaryCurrency: "USD",
    description: "Perform security audits on smart contracts and blockchain protocols.",
    requirements: "Security background, Solidity, formal verification",
    tags: JSON.stringify(["Security", "Auditing", "Solidity", "Formal Verification"]),
    applyUrl: "https://cryptojobslist.com/trail-of-bits-auditor",
    postedDate: new Date("2026-01-13"),
    isActive: 1,
  },
  {
    externalId: "remote3-013",
    source: "remote3",
    title: "Community Manager",
    company: "Polygon",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 70000,
    salaryMax: 110000,
    salaryCurrency: "USD",
    description: "Build and engage the Polygon developer community.",
    requirements: "Community management, Web3 knowledge, content creation",
    tags: JSON.stringify(["Community", "Web3", "Content", "Engagement"]),
    applyUrl: "https://remote3.co/polygon-community",
    postedDate: new Date("2026-01-12"),
    isActive: 1,
  },
  {
    externalId: "solana-014",
    source: "jobs.solana.com",
    title: "Technical Writer",
    company: "Solana Labs",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 80000,
    salaryMax: 120000,
    salaryCurrency: "USD",
    description: "Create developer documentation and technical content for Solana.",
    requirements: "Technical writing, blockchain knowledge, developer docs",
    tags: JSON.stringify(["Technical Writing", "Documentation", "Solana"]),
    applyUrl: "https://jobs.solana.com/technical-writer",
    postedDate: new Date("2026-01-11"),
    isActive: 1,
  },
  {
    externalId: "telegram-015",
    source: "telegram",
    title: "Full Stack Engineer",
    company: "1inch",
    location: "Remote",
    jobType: "Full-time",
    salaryMin: 120000,
    salaryMax: 170000,
    salaryCurrency: "USD",
    description: "Build DeFi aggregation platform and trading interfaces.",
    requirements: "Full stack development, React, Node.js, Web3",
    tags: JSON.stringify(["Full Stack", "React", "Node.js", "DeFi"]),
    applyUrl: "https://1inch.io/careers",
    postedDate: new Date("2026-01-13"),
    isActive: 1,
  },
];

async function seed() {
  console.log("Seeding database with sample jobs...");
  
  for (const job of sampleJobs) {
    try {
      await db.insert(jobs).values(job);
      console.log(`✓ Added: ${job.title} at ${job.company}`);
    } catch (error) {
      console.log(`✗ Skipped: ${job.title} (already exists)`);
    }
  }
  
  console.log(`\nSeeding complete! Added ${sampleJobs.length} jobs.`);
  process.exit(0);
}

seed().catch((error) => {
  console.error("Seeding failed:", error);
  process.exit(1);
});
